knife4j:
  enable: true
  setting:
    packages: com.meishubao.sample.controller
    enableOpenApi: false
    enableAfterScript: false
    enableGroup: false
    enableFooter: false
    enableFooterCustom: true
    footerCustomContent: Copyright &copy; 2022-[美术宝]
    enableDebug: true
  basic:
    enable: false
    username: xxms
    password: xxms