spring:
  redis:
    database: 1
    host: localhost
    port: 26379
    password: redispwd
    timeout: 15S
#    jedis:
#      pool:
#        min-idle: 5
#        max-idle: 10
#        max-active: 8
#        max-wait: 1ms
    lettuce:
      pool:
        min-idle: 5
        max-idle: 10
        max-active: 8
        max-wait: 1ms
      shutdown-timeout: 100ms
    message-queue:
      producer: true
      consumer: true