version: '3'
services:
  elasticsearch:
    image: elasticsearch:7.16.3
    container_name: elasticsearch
    networks:
      docker_net:
        aliases:
          - elasticsearch
    environment:
      - "cluster.name=elasticsearch" #设置集群名称为elasticsearch
      - "discovery.type=single-node" #以单一节点模式启动
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m" #设置使用jvm内存大小
      - "TZ=Asia/Shanghai"
    volumes:
      - /Users/voishion/work/server/docker/elasticsearch/plugins:/usr/share/elasticsearch/plugins
      - /Users/voishion/work/server/docker/elasticsearch/data:/usr/share/elasticsearch/data
      #- /Users/voishion/work/server/docker/elasticsearch/logs:/usr/share/elasticsearch/logs
    ports:
      - "9200:9200"
      - "9300:9300"

  kibana:
    image: kibana:7.16.3
    container_name: kibana
    networks:
      docker_net:
        aliases:
          - kibana
    links:
      - elasticsearch:es #可以用es这个域名访问elasticsearch服务
    depends_on:
      - elasticsearch #kibana在elasticsearch启动之后再启动
    environment:
      - "elasticsearch.hosts=http://es:9200" #设置访问elasticsearch的地址
      - "TZ=Asia/Shanghai"
    ports:
      - "5601:5601"

  logstash:
    container_name: logstash
    build:
      context: ./logstash
      dockerfile: Dockerfile
    networks:
      docker_net:
        aliases:
          - logstash
    links:
      - elasticsearch:es #可以用es这个域名访问elasticsearch服务
    volumes:
      # 任务跟踪文件目录
      - /Users/voishion/work/server/docker/logstash/tracking:/usr/share/logstash/tracking
    depends_on:
      - elasticsearch #kibana在elasticsearch启动之后再启动
    environment:
      - "xpack.monitoring.enabled=true"
      - "xpack.monitoring.elasticsearch.hosts=http://es:9200" # 解决logstash监控连接报错
      - "TZ=Asia/Shanghai"
    ports:
      - "4560:4560"

  elk:
    container_name: elk
    build:
      context: elk
      dockerfile: Dockerfile
    networks:
      docker_net:
        aliases:
          - elk
    ports:
      - "8080:8080"
    depends_on:
      - logstash
    links:
      - logstash:logstash

networks:
  docker_net:
    driver: bridge