version: '3'
services:
  elasticsearch:
    image: elasticsearch:7.16.3
    container_name: elasticsearch
    networks:
      elk_net:
        aliases:
          - elasticsearch
    environment:
      - "cluster.name=elasticsearch" #设置集群名称为elasticsearch
      - "discovery.type=single-node" #以单一节点模式启动
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m" #设置使用jvm内存大小
      - "TZ=Asia/Shanghai"
    volumes:
      - /Users/voishion/work/server/docker/elasticsearch/plugins:/usr/share/elasticsearch/plugins
      - /Users/voishion/work/server/docker/elasticsearch/data:/usr/share/elasticsearch/data
      #- /Users/voishion/work/server/docker/elasticsearch/logs:/usr/share/elasticsearch/logs
    ports:
      - "9200:9200"
      - "9300:9300"

  kibana:
    image: kibana:7.16.3
    container_name: kibana
    networks:
      elk_net:
        aliases:
          - kibana
    links:
      - elasticsearch:es #可以用es这个域名访问elasticsearch服务
    depends_on:
      - elasticsearch #kibana在elasticsearch启动之后再启动
    environment:
      - "elasticsearch.hosts=http://es:9200" #设置访问elasticsearch的地址
      - "TZ=Asia/Shanghai"
    ports:
      - "5601:5601"

  logstash:
    image: logstash:7.16.3
    container_name: logstash
    networks:
      elk_net:
        aliases:
          - logstash
    links:
      - elasticsearch:es #可以用es这个域名访问elasticsearch服务
    volumes:
      - /Users/voishion/work/server/docker/logstash/config/mysql-connector-java-8.0.23.jar:/mysql-connector-java-8.0.23.jar
      # 流水线配置
      - /Users/voishion/work/server/docker/logstash/config/pipelines.yml:/usr/share/logstash/config/pipelines.yml
      # 任务配置文件目录
      - /Users/voishion/work/server/docker/logstash/config/task:/usr/share/logstash/config/task
      # 任务跟踪文件目录
      - /Users/voishion/work/server/docker/logstash/config/tracking:/usr/share/logstash/config/tracking
    depends_on:
      - elasticsearch #kibana在elasticsearch启动之后再启动
    environment:
      - "xpack.monitoring.enabled=true"
      - "xpack.monitoring.elasticsearch.hosts=http://es:9200" # 解决logstash监控连接报错
      - "TZ=Asia/Shanghai"
    ports:
      - "4560:4560"

networks:
  elk_net:
    driver: bridge