spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot_study_sample?autoReconnect=true&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: abc123
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-flex:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/**/*Mapper.xml