# GraphQL
graphql:
  servlet:
    mapping: /graphql
    exception-handlers-enabled: true
    context-setting: per_request_with_instrumentation
  tools:
    schema-location-pattern: "**/*.graphqls"
  extended-scalars: BigDecimal
#GraphiQL Tool
graphiql:
  mapping: /graphiql
  endpoint:
    graphql: /graphql
  page-title: "GraphiQL Tool"
  cdn:
    enabled: true
    version: 0.11.11
  props:
    variables:
      #https://codemirror.net/demo/theme.html
      editorTheme: "darcula"
  headers:
    Authorization: "Bearer ayrih3548sncmcuw038smsu48"
