spring:
  cloud:
    stream:
      default-binder: kafka
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        output:
          destination: kafka-test-topic
        input:
          destination: kafka-test-topic