version: '3'
services:
  mysql:
    container_name: mysql
    build:
      context: ./mysql
      dockerfile: Dockerfile
    networks:
      docker_net:
        aliases:
          - mysql
    command: [
        'mysqld',
        '--default-authentication-plugin=mysql_native_password',
        '--innodb-buffer-pool-size=80M',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_0900_ai_ci',
        '--default-time-zone=+8:00',
        '--lower-case-table-names=1'
    ]
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: abc123
    volumes:
      - /Users/voishion/work/server/docker/mysql/conf:/etc/mysql/conf.d
      - /Users/voishion/work/server/docker/mysql/logs:/logs
      - /Users/voishion/work/server/docker/mysql/data:/var/lib/mysql
    ports:
      - "3306:3306"

  redis:
    image: redis:6.2.6
    container_name: redis
    networks:
      docker_net:
        aliases:
          - redis
    volumes:
      - /Users/voishion/work/server/docker/redis/conf/redis.conf:/etc/redis/redis.conf:rw
      - /Users/voishion/work/server/docker/redis/data:/data:rw
      - /Users/voishion/work/server/docker/redis/logs:/logs:rw
    command: redis-server /etc/redis/redis.conf --appendonly yes
    ports:
      - "6379:6379"

  nginx:
    image: nginx:1.21.5
    container_name: nginx
    networks:
      docker_net:
        aliases:
          - nginx
    environment:
      TZ: 'Asia/Shanghai'
    volumes:
      - /Users/voishion/work/server/docker/nginx/conf.d:/etc/nginx/conf.d
      - /Users/voishion/work/server/docker/nginx/log:/var/log/nginx
      - /Users/voishion/work/server/docker/nginx/deploy:/usr/share/nginx
    command: nginx -g 'daemon off;'
    ports:
      #- "80:80"
      - "37950:37950"
      - "37951:37951"

networks:
  docker_net:
    driver: bridge