feign:
  compression:
    request:
      enabled: true
      # 配置压缩支持的MIME TYPE
      mime-types: text/xml,application/xml,application/json
      # 配置压缩数据大小的下限
      min-request-size: 2048
    response:
      # 配置响应GZIP压缩
      enabled: true

knife4j:
  enable: true
  setting:
    enableOpenApi: false
    enableAfterScript: false
    enableFooter: false
    enableFooterCustom: true
    footerCustomContent: Copyright &copy; 2021-[美术宝](https://vip.meishubao.com/)
    enableHost: true
    enableHostText: https://dev.meixiu.mobi/music/pt
  cors: true
  basic:
    enable: false
    username: xxms
    password: xxms
