logging:
  config: classpath:log4j2-default.xml

spring:
  datasource:
    url: jdbc:mysql://rm-bp18993o867y4jg00.mysql.rds.aliyuncs.com/artworld_default?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: artworld_default
    password: Artworld_default_3306
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    url: redis://r-bp1gljed8xwgx8r5yc.redis.rds.aliyuncs.com:6379
    database: 1
    password: artWorld-devTest6379