// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserInfoCommunicationV0.proto

package com.meishubao.protobuf.protocol;

public final class UserInfoCommunicationV0 {
  private UserInfoCommunicationV0() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface UserInfoRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.meishubao.protobuf.protocol.UserInfoRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 userId = 1;</code>
     */
    long getUserId();
  }
  /**
   * Protobuf type {@code com.meishubao.protobuf.protocol.UserInfoRequest}
   */
  public  static final class UserInfoRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.meishubao.protobuf.protocol.UserInfoRequest)
      UserInfoRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use UserInfoRequest.newBuilder() to construct.
    private UserInfoRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UserInfoRequest() {
      userId_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private UserInfoRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              userId_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.meishubao.protobuf.protocol.UserInfoCommunicationV0.internal_static_com_meishubao_protobuf_protocol_UserInfoRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.meishubao.protobuf.protocol.UserInfoCommunicationV0.internal_static_com_meishubao_protobuf_protocol_UserInfoRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.meishubao.protobuf.protocol.UserInfoCommunicationV0.UserInfoRequest.class, com.meishubao.protobuf.protocol.UserInfoCommunicationV0.UserInfoRequest.Builder.class);
    }

    public static final int USERID_FIELD_NUMBER = 1;
    private long userId_;
    /**
     * <code>int64 userId = 1;</code>
     */
    public long getUserId() {
      return userId_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (userId_ != 0L) {
        output.writeInt64(1, userId_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (userId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, userId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.meishubao.protobuf.protocol.UserInfoCommunicationV0.UserInfoRequest)) {
        return super.equals(obj);
      }
      com.meishubao.protobuf.protocol.UserInfoCommunicationV0.UserInfoRequest other = (com.meishubao.protobuf.protocol.UserInfoCommunicationV0.UserInfoRequest) obj;

      boolean result = true;
      result = result && (getUserId()
          == other.getUserId());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + USERID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getUserId());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.meishubao.protobuf.protocol.UserInfoCommunicationV0.UserInfoRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.meishubao.protobuf.protocol.UserInfoCommunicationV0.UserInfoRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.meishubao.protobuf.protocol.UserInfoCommunicationV0.UserInfoRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.meishubao.protobuf.protocol.UserInfoCommunicationV0.UserInfoRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.meishubao.protobuf.protocol.UserInfoCommunicationV0.UserInfoRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.meishubao.protobuf.protocol.UserInfoCommunicationV0.UserInfoRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.meishubao.protobuf.protocol.UserInfoCommunicationV0.UserInfoRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.meishubao.protobuf.protocol.UserInfoCommunicationV0.UserInfoRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.meishubao.protobuf.protocol.UserInfoCommunicationV0.UserInfoRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.meishubao.protobuf.protocol.UserInfoCommunicationV0.UserInfoRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.meishubao.protobuf.protocol.UserInfoCommunicationV0.UserInfoRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.meishubao.protobuf.protocol.UserInfoCommunicationV0.UserInfoRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.meishubao.protobuf.protocol.UserInfoCommunicationV0.UserInfoRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.meishubao.protobuf.protocol.UserInfoRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.meishubao.protobuf.protocol.UserInfoRequest)
        com.meishubao.protobuf.protocol.UserInfoCommunicationV0.UserInfoRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.meishubao.protobuf.protocol.UserInfoCommunicationV0.internal_static_com_meishubao_protobuf_protocol_UserInfoRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.meishubao.protobuf.protocol.UserInfoCommunicationV0.internal_static_com_meishubao_protobuf_protocol_UserInfoRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.meishubao.protobuf.protocol.UserInfoCommunicationV0.UserInfoRequest.class, com.meishubao.protobuf.protocol.UserInfoCommunicationV0.UserInfoRequest.Builder.class);
      }

      // Construct using com.meishubao.protobuf.protocol.UserInfoCommunicationV0.UserInfoRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        userId_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.meishubao.protobuf.protocol.UserInfoCommunicationV0.internal_static_com_meishubao_protobuf_protocol_UserInfoRequest_descriptor;
      }

      @java.lang.Override
      public com.meishubao.protobuf.protocol.UserInfoCommunicationV0.UserInfoRequest getDefaultInstanceForType() {
        return com.meishubao.protobuf.protocol.UserInfoCommunicationV0.UserInfoRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.meishubao.protobuf.protocol.UserInfoCommunicationV0.UserInfoRequest build() {
        com.meishubao.protobuf.protocol.UserInfoCommunicationV0.UserInfoRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.meishubao.protobuf.protocol.UserInfoCommunicationV0.UserInfoRequest buildPartial() {
        com.meishubao.protobuf.protocol.UserInfoCommunicationV0.UserInfoRequest result = new com.meishubao.protobuf.protocol.UserInfoCommunicationV0.UserInfoRequest(this);
        result.userId_ = userId_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.meishubao.protobuf.protocol.UserInfoCommunicationV0.UserInfoRequest) {
          return mergeFrom((com.meishubao.protobuf.protocol.UserInfoCommunicationV0.UserInfoRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.meishubao.protobuf.protocol.UserInfoCommunicationV0.UserInfoRequest other) {
        if (other == com.meishubao.protobuf.protocol.UserInfoCommunicationV0.UserInfoRequest.getDefaultInstance()) return this;
        if (other.getUserId() != 0L) {
          setUserId(other.getUserId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.meishubao.protobuf.protocol.UserInfoCommunicationV0.UserInfoRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.meishubao.protobuf.protocol.UserInfoCommunicationV0.UserInfoRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long userId_ ;
      /**
       * <code>int64 userId = 1;</code>
       */
      public long getUserId() {
        return userId_;
      }
      /**
       * <code>int64 userId = 1;</code>
       */
      public Builder setUserId(long value) {
        
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 userId = 1;</code>
       */
      public Builder clearUserId() {
        
        userId_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.meishubao.protobuf.protocol.UserInfoRequest)
    }

    // @@protoc_insertion_point(class_scope:com.meishubao.protobuf.protocol.UserInfoRequest)
    private static final com.meishubao.protobuf.protocol.UserInfoCommunicationV0.UserInfoRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.meishubao.protobuf.protocol.UserInfoCommunicationV0.UserInfoRequest();
    }

    public static com.meishubao.protobuf.protocol.UserInfoCommunicationV0.UserInfoRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UserInfoRequest>
        PARSER = new com.google.protobuf.AbstractParser<UserInfoRequest>() {
      @java.lang.Override
      public UserInfoRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new UserInfoRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<UserInfoRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UserInfoRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.meishubao.protobuf.protocol.UserInfoCommunicationV0.UserInfoRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface UserInfoResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.meishubao.protobuf.protocol.UserInfoResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 userType = 1;</code>
     */
    int getUserType();

    /**
     * <code>string mobile = 2;</code>
     */
    java.lang.String getMobile();
    /**
     * <code>string mobile = 2;</code>
     */
    com.google.protobuf.ByteString
        getMobileBytes();
  }
  /**
   * Protobuf type {@code com.meishubao.protobuf.protocol.UserInfoResponse}
   */
  public  static final class UserInfoResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.meishubao.protobuf.protocol.UserInfoResponse)
      UserInfoResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use UserInfoResponse.newBuilder() to construct.
    private UserInfoResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UserInfoResponse() {
      userType_ = 0;
      mobile_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private UserInfoResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              userType_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              mobile_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.meishubao.protobuf.protocol.UserInfoCommunicationV0.internal_static_com_meishubao_protobuf_protocol_UserInfoResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.meishubao.protobuf.protocol.UserInfoCommunicationV0.internal_static_com_meishubao_protobuf_protocol_UserInfoResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.meishubao.protobuf.protocol.UserInfoCommunicationV0.UserInfoResponse.class, com.meishubao.protobuf.protocol.UserInfoCommunicationV0.UserInfoResponse.Builder.class);
    }

    public static final int USERTYPE_FIELD_NUMBER = 1;
    private int userType_;
    /**
     * <code>int32 userType = 1;</code>
     */
    public int getUserType() {
      return userType_;
    }

    public static final int MOBILE_FIELD_NUMBER = 2;
    private volatile java.lang.Object mobile_;
    /**
     * <code>string mobile = 2;</code>
     */
    public java.lang.String getMobile() {
      java.lang.Object ref = mobile_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        mobile_ = s;
        return s;
      }
    }
    /**
     * <code>string mobile = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMobileBytes() {
      java.lang.Object ref = mobile_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        mobile_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (userType_ != 0) {
        output.writeInt32(1, userType_);
      }
      if (!getMobileBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, mobile_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (userType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, userType_);
      }
      if (!getMobileBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, mobile_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.meishubao.protobuf.protocol.UserInfoCommunicationV0.UserInfoResponse)) {
        return super.equals(obj);
      }
      com.meishubao.protobuf.protocol.UserInfoCommunicationV0.UserInfoResponse other = (com.meishubao.protobuf.protocol.UserInfoCommunicationV0.UserInfoResponse) obj;

      boolean result = true;
      result = result && (getUserType()
          == other.getUserType());
      result = result && getMobile()
          .equals(other.getMobile());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + USERTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getUserType();
      hash = (37 * hash) + MOBILE_FIELD_NUMBER;
      hash = (53 * hash) + getMobile().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.meishubao.protobuf.protocol.UserInfoCommunicationV0.UserInfoResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.meishubao.protobuf.protocol.UserInfoCommunicationV0.UserInfoResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.meishubao.protobuf.protocol.UserInfoCommunicationV0.UserInfoResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.meishubao.protobuf.protocol.UserInfoCommunicationV0.UserInfoResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.meishubao.protobuf.protocol.UserInfoCommunicationV0.UserInfoResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.meishubao.protobuf.protocol.UserInfoCommunicationV0.UserInfoResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.meishubao.protobuf.protocol.UserInfoCommunicationV0.UserInfoResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.meishubao.protobuf.protocol.UserInfoCommunicationV0.UserInfoResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.meishubao.protobuf.protocol.UserInfoCommunicationV0.UserInfoResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.meishubao.protobuf.protocol.UserInfoCommunicationV0.UserInfoResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.meishubao.protobuf.protocol.UserInfoCommunicationV0.UserInfoResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.meishubao.protobuf.protocol.UserInfoCommunicationV0.UserInfoResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.meishubao.protobuf.protocol.UserInfoCommunicationV0.UserInfoResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.meishubao.protobuf.protocol.UserInfoResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.meishubao.protobuf.protocol.UserInfoResponse)
        com.meishubao.protobuf.protocol.UserInfoCommunicationV0.UserInfoResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.meishubao.protobuf.protocol.UserInfoCommunicationV0.internal_static_com_meishubao_protobuf_protocol_UserInfoResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.meishubao.protobuf.protocol.UserInfoCommunicationV0.internal_static_com_meishubao_protobuf_protocol_UserInfoResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.meishubao.protobuf.protocol.UserInfoCommunicationV0.UserInfoResponse.class, com.meishubao.protobuf.protocol.UserInfoCommunicationV0.UserInfoResponse.Builder.class);
      }

      // Construct using com.meishubao.protobuf.protocol.UserInfoCommunicationV0.UserInfoResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        userType_ = 0;

        mobile_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.meishubao.protobuf.protocol.UserInfoCommunicationV0.internal_static_com_meishubao_protobuf_protocol_UserInfoResponse_descriptor;
      }

      @java.lang.Override
      public com.meishubao.protobuf.protocol.UserInfoCommunicationV0.UserInfoResponse getDefaultInstanceForType() {
        return com.meishubao.protobuf.protocol.UserInfoCommunicationV0.UserInfoResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.meishubao.protobuf.protocol.UserInfoCommunicationV0.UserInfoResponse build() {
        com.meishubao.protobuf.protocol.UserInfoCommunicationV0.UserInfoResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.meishubao.protobuf.protocol.UserInfoCommunicationV0.UserInfoResponse buildPartial() {
        com.meishubao.protobuf.protocol.UserInfoCommunicationV0.UserInfoResponse result = new com.meishubao.protobuf.protocol.UserInfoCommunicationV0.UserInfoResponse(this);
        result.userType_ = userType_;
        result.mobile_ = mobile_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.meishubao.protobuf.protocol.UserInfoCommunicationV0.UserInfoResponse) {
          return mergeFrom((com.meishubao.protobuf.protocol.UserInfoCommunicationV0.UserInfoResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.meishubao.protobuf.protocol.UserInfoCommunicationV0.UserInfoResponse other) {
        if (other == com.meishubao.protobuf.protocol.UserInfoCommunicationV0.UserInfoResponse.getDefaultInstance()) return this;
        if (other.getUserType() != 0) {
          setUserType(other.getUserType());
        }
        if (!other.getMobile().isEmpty()) {
          mobile_ = other.mobile_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.meishubao.protobuf.protocol.UserInfoCommunicationV0.UserInfoResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.meishubao.protobuf.protocol.UserInfoCommunicationV0.UserInfoResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int userType_ ;
      /**
       * <code>int32 userType = 1;</code>
       */
      public int getUserType() {
        return userType_;
      }
      /**
       * <code>int32 userType = 1;</code>
       */
      public Builder setUserType(int value) {
        
        userType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 userType = 1;</code>
       */
      public Builder clearUserType() {
        
        userType_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object mobile_ = "";
      /**
       * <code>string mobile = 2;</code>
       */
      public java.lang.String getMobile() {
        java.lang.Object ref = mobile_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          mobile_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string mobile = 2;</code>
       */
      public com.google.protobuf.ByteString
          getMobileBytes() {
        java.lang.Object ref = mobile_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          mobile_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string mobile = 2;</code>
       */
      public Builder setMobile(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        mobile_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string mobile = 2;</code>
       */
      public Builder clearMobile() {
        
        mobile_ = getDefaultInstance().getMobile();
        onChanged();
        return this;
      }
      /**
       * <code>string mobile = 2;</code>
       */
      public Builder setMobileBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        mobile_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.meishubao.protobuf.protocol.UserInfoResponse)
    }

    // @@protoc_insertion_point(class_scope:com.meishubao.protobuf.protocol.UserInfoResponse)
    private static final com.meishubao.protobuf.protocol.UserInfoCommunicationV0.UserInfoResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.meishubao.protobuf.protocol.UserInfoCommunicationV0.UserInfoResponse();
    }

    public static com.meishubao.protobuf.protocol.UserInfoCommunicationV0.UserInfoResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UserInfoResponse>
        PARSER = new com.google.protobuf.AbstractParser<UserInfoResponse>() {
      @java.lang.Override
      public UserInfoResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new UserInfoResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<UserInfoResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UserInfoResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.meishubao.protobuf.protocol.UserInfoCommunicationV0.UserInfoResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_meishubao_protobuf_protocol_UserInfoRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_meishubao_protobuf_protocol_UserInfoRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_meishubao_protobuf_protocol_UserInfoResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_meishubao_protobuf_protocol_UserInfoResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035UserInfoCommunicationV0.proto\022\037com.mei" +
      "shubao.protobuf.protocol\"!\n\017UserInfoRequ" +
      "est\022\016\n\006userId\030\001 \001(\003\"4\n\020UserInfoResponse\022" +
      "\020\n\010userType\030\001 \001(\005\022\016\n\006mobile\030\002 \001(\tb\006proto" +
      "3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_meishubao_protobuf_protocol_UserInfoRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_meishubao_protobuf_protocol_UserInfoRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_meishubao_protobuf_protocol_UserInfoRequest_descriptor,
        new java.lang.String[] { "UserId", });
    internal_static_com_meishubao_protobuf_protocol_UserInfoResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_meishubao_protobuf_protocol_UserInfoResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_meishubao_protobuf_protocol_UserInfoResponse_descriptor,
        new java.lang.String[] { "UserType", "Mobile", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
